# Generated by Django 5.0.1 on 2024-01-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('concepto', models.CharField(max_length=300)),
                ('comentarios', models.TextField()),
                ('diario', models.TextField()),
                ('porcGg', models.DecimalField(decimal_places=4, max_digits=6)),
                ('porcBi', models.DecimalField(decimal_places=4, max_digits=6)),
                ('gastosFijos', models.DecimalField(decimal_places=4, max_digits=10)),
                ('image', models.ImageField(default='null', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
