# Generated by Django 5.0.1 on 2024-01-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_obra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articleprueba',
        ),
    ]
