# Generated by Django 5.0.1 on 2024-02-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_alter_partresult_empr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partresult',
            name='empr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.empr'),
        ),
        migrations.AlterField(
            model_name='partresult',
            name='fase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.fase'),
        ),
        migrations.AlterField(
            model_name='partresult',
            name='obra',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra'),
        ),
        migrations.AlterField(
            model_name='partresult',
            name='zona',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.zona'),
        ),
    ]
