# Generated by Django 5.0.1 on 2024-01-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_delete_articleprueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
