# Generated by Django 5.0.1 on 2024-02-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_alter_partgendb_precio_unit_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='precio_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
