# Generated by Django 5.0.1 on 2024-01-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_obra_ended'),
        ('user', '0009_alter_employee_id_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='id_org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.org'),
        ),
    ]
