# Generated by Django 5.0.1 on 2024-01-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0006_capitulo_unit_fase_partgendb_partresult_partgen_zona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='id_Obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.obra'),
        ),
        migrations.AlterField(
            model_name='partresult',
            name='id_Obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.obra'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='id_Obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.obra'),
        ),
    ]
