# Generated by Django 5.0.1 on 2024-02-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0008_alter_partgendb_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partgendb',
            name='comentarios',
            field=models.TextField(null=True),
        ),
    ]
