# Generated by Django 5.0.1 on 2024-02-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0011_alter_partgendb_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partresult',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='partresult',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
