# Generated by Django 5.0.1 on 2024-02-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0012_remove_partresult_cantidad_alter_partresult_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase',
            old_name='id_Obra',
            new_name='obra',
        ),
        migrations.RenameField(
            model_name='partgen',
            old_name='id_partgendb',
            new_name='partgendb',
        ),
        migrations.RenameField(
            model_name='partgen',
            old_name='id_partresult',
            new_name='partresult',
        ),
        migrations.RenameField(
            model_name='partgendb',
            old_name='id_capitulo',
            new_name='capitulo',
        ),
        migrations.RenameField(
            model_name='partgendb',
            old_name='id_org',
            new_name='org',
        ),
        migrations.RenameField(
            model_name='partgendb',
            old_name='id_unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='partresult',
            old_name='id_fase',
            new_name='fase',
        ),
        migrations.RenameField(
            model_name='partresult',
            old_name='id_Obra',
            new_name='obra',
        ),
        migrations.RenameField(
            model_name='partresult',
            old_name='id_zona',
            new_name='zona',
        ),
        migrations.RenameField(
            model_name='zona',
            old_name='id_Obra',
            new_name='obra',
        ),
    ]
