# Generated by Django 5.0.1 on 2024-01-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.org'),
        ),
    ]
