# Generated by Django 5.0.1 on 2024-01-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_id_org'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
