# Generated by Django 5.0.1 on 2024-01-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_employee_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.org'),
        ),
    ]
